### PR TITLE
Fixed broken README.md

### LINKED ISSUE #97: Broken README point
A point in README under `extras` i.e. `cd ..` is broken, the ending backtick is missing.
Please assign me this.

### PR DESCRIPTION
**Pull request by Monal5031**
Fixes #97

### CODE REVIEW

**Review by anshumanv — APPROVED** [review]

**Comment by singh1114** [comment]
@Monal5031 There is a typo in the README.md file at line 36. Please correct it and add the commit to this PR.

**Comment by Monal5031** [comment]
Shall I update the same issue or create a new one?

**Review by RajuKoushik — COMMENTED** [review]
👍

**Comment by pombredanne** [comment]
@Monal5031 @anshumanv Thanks!

**Pull request merged**
