### PR TITLE
Fix typo on pip install in README

### PR DESCRIPTION
**Pull request by pgier**

### CODE REVIEW

**Comment by singh1114** [comment]
Actually, we need `-r` for running the command recursively.
BTW, thanks for the PR.

**Comment by pgier** [comment]
I'm not sure I understand your comment about running recursively.
The -r option to "pip install" is to use a requirements.txt file and not related to recursion.
If you run pip install without the -r option, then it thinks "requirements.txt" is the name of a package.

**Comment by singh1114** [comment]
So basically, we don't really need the commit. Right?

**Comment by singh1114** [comment]
I am so sorry. I thought that you removed the `-r` part. 
My bad. Thanks for figuring it out.
Can you please resend the PR to the `develop` branch.

**Comment by pgier** [comment]
Ok, created PR #62 against the develop branch

**Pull request closed without merging**
