### PR TITLE
Added head block

### PR DESCRIPTION
**Pull request by srbcheema1**
A small fix and added block for head contents

### CODE REVIEW

**Comment by pombredanne** [comment]
@srbcheema1 Thanks! I would need your signoff in your commit messages

**Comment by singh1114** [comment]
@srbcheema1 Great! Can you please squash your commits.

**Comment by srbcheema1** [comment]
@singh1114 I just kept both different because both of them were doing different job.
one was removing a typo and another was adding blocks.
still if you suggest then i will squash them into one

**Comment by pombredanne** [comment]
LTGM! merging.

**Comment by pombredanne** [comment]
Thanks :+1:

**Comment by srbcheema1** [comment]
it was pleasure for me to contribute to this organisation :relaxed:

**Pull request merged**
